rdkcentral/Ripple

core/launcher/src/launcher_ffi.rs, core/launcher/src/launcher_lifecycle_processor.rs, core/launcher/src/manager/app_launcher.rs, core/launcher/src/manager/container_manager.rs, core/main/src/firebolt/handlers/device_rpc.rs, core/main/src/firebolt/handlers/metrics_rpc.rs, core/main/src/service/apps/delegated_launcher_handler.rs, core/main/src/service/apps/provider_broker.rs, core/main/src/service/extn/ripple_client.rs, core/sdk/src/api/device/device_operator.rs, core/sdk/src/api/firebolt/fb_lifecycle_management.rs, core/sdk/src/extn/client/extn_client.rs, core/sdk/src/extn/client/extn_sender.rs, core/sdk/src/utils/logger.rs, device/thunder_ripple_sdk/src/bootstrap/setup_thunder_pool_step.rs, distributor/general/src/distributor_general_ffi.rs
=> fix: Certification Issues fixes #131 #133 #134

NOTICE
Fixes the compliance issue reported in BD-1191
=> Update NOTICE fixes  #142

core/main/src/firebolt/handlers/secure_storage_rpc.rs, core/sdk/src/api/firebolt/fb_secure_storage.rs, core/sdk/src/extn/extn_client_message.rs
=> feat : extn response enum for secure storage added.

core/main/src/bootstrap/extn/load_extn_step.rs, core/main/src/processor/storage/storage_manager.rs, core/main/src/service/extn/ripple_client.rs, core/main/src/state/extn_state.rs, core/sdk/src/api/firebolt/fb_metrics.rs, core/sdk/src/extn/client/extn_client.rs, core/sdk/src/extn/client/extn_sender.rs, core/sdk/src/framework/ripple_contract.rs, device/thunder/src/bootstrap/boot_thunder_channel.rs, device/thunder/src/lib.rs, device/thunder_ripple_sdk/src/bootstrap/boot_thunder.rs, device/thunder_ripple_sdk/src/bootstrap/get_config_step.rs, device/thunder_ripple_sdk/src/bootstrap/setup_thunder_pool_step.rs, device/thunder_ripple_sdk/src/bootstrap/setup_thunder_processors.rs, device/thunder_ripple_sdk/src/client/jsonrpc_method_locator.rs, device/thunder_ripple_sdk/src/client/plugin_manager.rs, device/thunder_ripple_sdk/src/lib.rs, device/thunder_ripple_sdk/src/processors/events/thunder_event_handlers.rs, device/thunder_ripple_sdk/src/processors/thunder_browser.rs, device/thunder_ripple_sdk/src/processors/thunder_device_info.rs, device/thunder_ripple_sdk/src/processors/thunder_events.rs, device/thunder_ripple_sdk/src/processors/thunder_persistent_store.rs, device/thunder_ripple_sdk/src/processors/thunder_remote.rs, device/thunder_ripple_sdk/src/processors/thunder_wifi.rs, device/thunder_ripple_sdk/src/processors/thunder_window_manager.rs, device/thunder_ripple_sdk/src/thunder_state.rs, distributor/general/src/distributor_general_ffi.rs
=> feat: Metrics Upgrades and Performance improvements

Cargo.toml, core/launcher/Cargo.toml, core/main/Cargo.toml, core/main/src/processor/lifecycle_management_processor.rs, core/main/src/state/cap/permitted_state.rs, core/sdk/Cargo.toml, core/sdk/src/extn/client/extn_client.rs, device/thunder/Cargo.toml, device/thunder_ripple_sdk/Cargo.toml, distributor/general/Cargo.toml, examples/rpc_extn/Cargo.toml
=> feat: Certification Updates + Use Workspace version across packages

core/main/src/firebolt/handlers/advertising_rpc.rs, core/main/src/firebolt/handlers/secure_storage_rpc.rs, core/main/src/processor/storage/default_storage_properties.rs, core/sdk/src/api/firebolt/fb_secure_storage.rs, core/sdk/src/api/storage_property.rs
feat: add advertising.setSkipRestriction manage API
=> feat: add secureStorage.setForApp manage APIs

core/sdk/src/api/device/device_peristence.rs, core/sdk/src/api/distributor/distributor_privacy.rs, core/sdk/src/api/distributor/distributor_usergrants.rs, core/sdk/src/api/firebolt/fb_authentication.rs, core/sdk/src/api/firebolt/fb_secure_storage.rs, core/sdk/src/api/manifest/persistent_store.rs, core/sdk/src/api/session.rs, core/sdk/src/api/storage_property.rs, core/sdk/src/api/usergrant_entry.rs, core/sdk/src/extn/client/extn_client.rs, core/sdk/src/extn/client/extn_processor.rs, core/sdk/src/framework/mod.rs, core/sdk/src/framework/ripple_contract.rs, device/thunder/src/thunder_ffi.rs, distributor/general/src/distributor_general_ffi.rs, distributor/general/src/general_token_processor.rs, docs/adr/contract_adjectives.md
Provide a better design for contracts
https://github.com/rdkcentral/Ripple/blob/adjectives/docs/adr/contract_adjectives.md
https://github.com/rdkcentral/Ripple/blob/adjectives/docs/adr/contract_adjectives.md
=> feat: Adjectives ADR + Implementation

core/main/src/bootstrap/extn/load_session_step.rs, core/main/src/firebolt/handlers/account_rpc.rs, core/main/src/firebolt/handlers/authentication_rpc.rs, core/main/src/service/user_grants.rs, core/main/src/state/platform_state.rs, device/thunder_ripple_sdk/src/processors/thunder_device_info.rs, device/thunder_ripple_sdk/src/processors/thunder_persistent_store.rs
Fixes for below issues
1. Authentication for distributor is not setup along with platform
2. Thunder Persistent store doesnt return an error for all cases
3. Issues with conversion layer for Thunder Voice guidance layer
1. Reuse the token implementation for all types
2. Add error cases for the the Thunder Persistent store
3. Add the accurate conversion logic for voice guidance.
=> fix: Bug fixes based on OSS Cert testing

core/main/src/service/apps/delegated_launcher_handler.rs, core/sdk/src/api/firebolt/fb_capabilities.rs, core/sdk/src/extn/client/extn_client.rs, core/sdk/src/extn/client/extn_processor.rs, core/sdk/src/framework/ripple_contract.rs, core/sdk/src/utils/serde_utils.rs
1. Fix for making adjective contracts to be more readable in the logs. Added unit tests for them as well.
2. Add logging for standalone requests.
3. Add logging  for extension to contract mapping
=> fix: Adjective fixes and log cleanup

core/main/src/service/apps/delegated_launcher_handler.rs, core/sdk/src/utils/serde_utils.rs
=> fix: active session id does not get reset when app goes to inactive

core/main/src/firebolt/handlers/secure_storage_rpc.rs, core/sdk/src/api/firebolt/fb_secure_storage.rs, distributor/general/src/general_securestorage_processor.rs
=> feat: Port secureStorage manage APIs

Cargo.toml, core/launcher/Cargo.toml, core/launcher/src/manager/app_launcher.rs, core/main/Cargo.toml, core/main/src/bootstrap/manifest/device.rs, core/main/src/bootstrap/manifest/extn.rs, core/main/src/firebolt/handlers/audio_description_rpc.rs, core/main/src/firebolt/handlers/capabilities_rpc.rs, core/main/src/state/firebolt-open-rpc.json, core/sdk/Cargo.toml, core/sdk/src/api/apps.rs, core/tdk/Cargo.toml, device/thunder/Cargo.toml, device/thunder_ripple_sdk/Cargo.toml, distributor/general/Cargo.toml, examples/rpc_extn/Cargo.toml, examples/tm_extn/Cargo.toml, ripple
Removes /opt and other overrides for manifest making them compile time build configuration
Upgrades the developer run scripts with right build flags
Upgrades version numbers
First step to make Ripple production ready.
Using Rust configuration flags
Execute ./ripple run <ip_address>
=> feat: Changes for 1.0.0

core/main/src/firebolt/handlers/authentication_rpc.rs, core/main/src/state/platform_state.rs, core/sdk/src/api/manifest/device_manifest.rs
* fix: Remove backup for Root token for device
* fix: Cleanup feature flag for device tokens
Cherry Pick from 327
=> Fix auth (#327) Cherry-pick 

core/main/src/firebolt/handlers/authentication_rpc.rs
Fix error message to not supported error with corresponding error code -50100
=> fix: Fixed error message & code to: not supported & -50100

core/main/src/service/user_grants.rs
Fix for settings throwing custom error
Bug fix. There was an unsafe unwrap in grant policy map processing from manifest file. 
=> fix: settings throwing custom error

core/main/src/service/user_grants.rs
Fix for settings throwing custom error
Bug fix. There was an unsafe unwrap in grant policy map processing from manifest file.
=> fix: settings throwing custom error (#332)

core/launcher/src/manager/app_launcher.rs, core/main/src/firebolt/handlers/advertising_rpc.rs, core/main/src/firebolt/handlers/device_rpc.rs, core/main/src/firebolt/handlers/privacy_rpc.rs, core/main/src/processor/account_link_processor.rs
Bug fix
There were many unsafe `unwrap()` associated with account session
Cleaned up code to avoid the usage of unsafe `unwrap()`
=> Fix: Removed unsafe unwrap in account session

core/main/src/firebolt/handlers/metrics_rpc.rs
uncomment validate_metrics_action_type()
bug fix
uncomment validate_metrics_action_type()
=> fix: uncomment validate_metrics_action_type()

core/main/src/firebolt/handlers/voice_guidance_rpc.rs
Added correct error code for VoiceGuidance.setSpeed APIs
To make the error code consistent .
=> fix: VoiceGuidance.setSpeed Negative Scenario Failing With Unexpected Error code

ripple
=> chore: code coverage test

core/main/src/firebolt/firebolt_gateway.rs
Refer https://github.com/rdkcentral/Ripple/pull/362
Refer https://github.com/rdkcentral/Ripple/pull/362
Refer https://github.com/rdkcentral/Ripple/pull/362
Refer https://github.com/rdkcentral/Ripple/pull/362
=> fix Add missing patch from 1.0.1 #362

Cargo.toml, core/launcher/Cargo.toml, core/main/Cargo.toml, core/sdk/Cargo.toml, core/tdk/Cargo.toml, device/thunder/Cargo.toml, device/thunder_ripple_sdk/Cargo.toml, distributor/general/Cargo.toml, examples/rpc_extn/Cargo.toml, examples/tm_extn/Cargo.toml
1.0.1 version bump
On startup look for version logs for 1.0.1
=> chore: Bump 1.0.1

Cargo.toml, core/launcher/Cargo.toml, core/main/Cargo.toml, core/sdk/Cargo.toml, core/tdk/Cargo.toml, device/thunder/Cargo.toml, device/thunder_ripple_sdk/Cargo.toml, distributor/general/Cargo.toml, examples/rpc_extn/Cargo.toml, examples/tm_extn/Cargo.toml
=> bump: version 1.1.0

core/main/src/processor/main_context_processor.rs, core/sdk/src/extn/client/extn_client.rs
=> Cherry-pick from #379

.github/workflows/Build.yml
Add code coverage % in pull request check.
This is changes is required in order to maintain quality code
=> Add code coverage pr check

ripple
=> chore: test post merge workflow

.github/workflows/post-merge.yml
=> fix: remove extra " in post merge yaml

core/sdk/src/api/device/entertainment_data.rs
=> Make intent deserialization more forgiving (#405)

core/main/src/processor/main_context_processor.rs, core/sdk/src/api/app_catalog.rs
=> App Management: Fixed race condition for ripple catalog update listener registration.

device/thunder_ripple_sdk/src/client/thunder_plugin.rs
=> fix: change to open source callsign for PackageManager

.github/workflows/Build.yml, core/sdk/src/api/storage_property.rs
=> accessibility.onClosedCaptionsSettingsChanged: Fixed missing event when closedcaptions.setPreferredLanguages is called.

.github/workflows/Build.yml, .github/workflows/post-merge.yml
=> Update coverage script

.github/workflows/Build.yml, .github/workflows/post-merge.yml
=> update coverage threshold script

core/main/src/state/cap/permitted_state.rs, core/sdk/src/api/distributor/distributor_permissions.rs, core/sdk/src/api/session.rs
=> add optional permission payload to permission request

device/thunder_ripple_sdk/Cargo.toml
=> feat: NO-JIRA: Updated Cargo.toml.

.github/workflows/Build.yml
=> fix checkout locked_actions_branch branch to read coverage threshold

.github/workflows/Build.yml, core/main/src/firebolt/firebolt_ws.rs, core/main/src/processor/main_context_processor.rs, core/main/src/service/context_manager.rs, core/main/src/state/cap/permitted_state.rs, core/sdk/src/api/config.rs, core/sdk/src/api/context.rs
=> Features: Set defaults from manifest on boot

core/main/Cargo.toml, core/main/src/firebolt/handlers/device_rpc.rs, core/main/src/processor/metrics_processor.rs, core/main/src/service/apps/apps_updater.rs, core/main/src/service/telemetry_builder.rs, core/main/src/state/bootstrap_state.rs, core/main/src/state/metrics_state.rs, core/main/src/state/platform_state.rs
=> RPPL-1808:Read /etc/rippleversion.txt and update version

core/sdk/src/api/device/entertainment_data.rs
Fix the parameters.initialization response as per openRpc
=> fix: Parameters.initialization response as per openRpc

core/sdk/src/extn/client/extn_client.rs, device/thunder_ripple_sdk/src/processors/thunder_package_manager.rs
=> Package Manager: Make operation timeout configurable

core/sdk/Cargo.toml, core/sdk/src/api/firebolt/fb_capabilities.rs, device/thunder_ripple_sdk/Cargo.toml, device/thunder_ripple_sdk/src/lib.rs, device/thunder_ripple_sdk/src/processors/thunder_package_manager.rs, device/thunder_ripple_sdk/src/tests/contracts/thunder_package_manager_pacts.rs, device/thunder_ripple_sdk/src/tests/thunder_client_pool_test_utility.rs
=> feat: added contract tests for device thunder package manager

core/main/src/bootstrap/manifest/device.rs, core/main/src/bootstrap/manifest/extn.rs, core/sdk/src/api/device/entertainment_data.rs, systemd/ripple.service
=> RPPL-1712: Update recipe to use prod binaries and add ExecStartPre, ExecStartPost in ripple service file

core/sdk/src/api/apps.rs, core/sdk/src/api/device/device_browser.rs, core/sdk/src/api/device/device_request.rs, core/sdk/src/api/device/device_user_grants_data.rs, core/sdk/src/api/device/entertainment_data.rs, core/sdk/src/api/distributor/distributor_request.rs, core/sdk/src/api/firebolt/fb_advertising.rs, core/sdk/src/api/firebolt/fb_openrpc.rs, core/sdk/src/api/firebolt/provider.rs, core/sdk/src/api/manifest/device_manifest.rs, core/sdk/src/api/manifest/extn_manifest.rs, core/sdk/src/api/manifest/remote_feature.rs, core/sdk/src/extn/extn_client_message.rs, core/sdk/src/framework/ripple_contract.rs
=> Add api tests enable partial eq only test - Optimize conditional compilation for PartialEq trait

device/thunder_ripple_sdk/src/tests/contracts/thunder_package_manager_pacts.rs
=> fix: disable package manager contract test - init

core/sdk/src/api/firebolt/fb_secure_storage.rs
=> Cleanup secure storage

core/sdk/src/api/distributor/distributor_privacy.rs, core/sdk/src/api/distributor/distributor_usergrants.rs, core/sdk/src/api/firebolt/fb_discovery.rs, core/sdk/src/api/session.rs, core/sdk/src/utils/error.rs
=> Cleanup ess xvp

core/main/src/service/apps/delegated_launcher_handler.rs
=> feat: removed appError from lifeCyle errors send to sift

.github/workflows/Build.yml, core/sdk/src/extn/client/extn_client.rs, device/thunder_ripple_sdk/src/processors/thunder_package_manager.rs
=> Package Manager: Make operation timeout configurable (#495)

core/main/src/firebolt/firebolt_gateway.rs, core/main/src/firebolt/rpc_router.rs, core/sdk/src/api/gateway/rpc_gateway_api.rs
For triage and observability, we would like to understand the success of firebolt interactions as well as response time of firebolt api's in the field. 
The changes here are to modify firebolt response log message to make it RDKTelemetry 1.0 friendly. 
If required,  markers can be created and triage can be done via RDK Telemetry
The new log messages of firebolt API response will be printed in the following format
```
[INFO][ripple::firebolt::rpc_router][gateway]-Sending Firebolt response: <appId>,<method>,<status>,<duration> 
```
where
```
appId <string>
method <string> (will include module and method)
status (errorCode) (1 if pass, else the errorCode)
duration (duration in milliseconds)
```
=> feat: Telemetry: RDKTelemetry 1.0 friendly messages for Firebolt interaction

core/sdk/src/api/firebolt/fb_metrics.rs
Add conversion (to i32 & f32) function 
=> Cleanup metrics

.github/workflows/Build.yml, core/main/src/firebolt/handlers/authentication_rpc.rs, core/sdk/src/extn/client/extn_client.rs, device/thunder_ripple_sdk/src/client/plugin_manager.rs, device/thunder_ripple_sdk/src/client/thunder_client_pool.rs, device/thunder_ripple_sdk/src/processors/thunder_package_manager.rs, device/thunder_ripple_sdk/src/tests/contracts/thunder_package_manager_pacts.rs
=> 1.5.rc --> main: Merge

core/main/src/firebolt/handlers/advertising_rpc.rs
=> fix: advertising id no params

core/launcher/src/manager/app_launcher.rs, core/launcher/src/manager/container_manager.rs, core/launcher/src/manager/view_manager.rs, core/main/src/firebolt/firebolt_gatekeeper.rs, core/main/src/firebolt/handlers/closed_captions_rpc.rs, core/main/src/firebolt/rpc_router.rs, core/main/src/processor/account_link_processor.rs, core/main/src/processor/storage/storage_manager_utils.rs, core/main/src/service/apps/app_events.rs, core/main/src/service/apps/delegated_launcher_handler.rs, core/main/src/service/user_grants.rs, core/main/src/state/openrpc_state.rs, core/sdk/src/api/device/device_browser.rs, core/sdk/src/api/device/device_user_grants_data.rs, core/sdk/src/api/firebolt/fb_metrics.rs, core/sdk/src/api/gateway/rpc_gateway_api.rs, core/sdk/src/extn/client/extn_sender.rs, core/sdk/src/extn/extn_id.rs, core/sdk/src/framework/bootstrap.rs, device/thunder_ripple_sdk/src/client/thunder_client.rs, device/thunder_ripple_sdk/src/client/thunder_client_pool.rs, device/thunder_ripple_sdk/src/processors/thunder_device_info.rs, device/thunder_ripple_sdk/src/utils.rs
Removes ~90 `.unwrap()` calls in favor of other Rust programming paradigms that prove the state of the enum instead of generating a `panic!()` on unexpected case.
Most the the replaced code was written like so, with the conditional check to handle the unwanted variant (`None` in this case) and then the call to `unwrap()` to extract the value.
```
if entry.is_none() {
error!(
"on_app_state_change: app_id={} Not found",
state_change.container_props.name
);
return;
}
// safe to unwrap
let app = entry.unwrap();
```
However `unwrap()` under the hood is just a `panic!` when the `None` variant is encountered like so.
```
if entry.is_none() {
error!(
"on_app_state_change: app_id={} Not found",
state_change.container_props.name
);
return;
}
// safe to unwrap
let app = match entry {
Some(value) => …
```
=> Remove unwraps

core/sdk/src/api/firebolt/fb_discovery.rs
=> Rewrite unit tests without DpabDelegate

device/thunder_ripple_sdk/src/processors/thunder_device_info.rs
=> feat: Fixed the TimeZone retrieval issue in the context.

device/thunder_ripple_sdk/src/processors/thunder_package_manager.rs
=> Fixed removal from active operations map when operation completes

core/main/src/processor/storage/storage_manager.rs
Generate events when setting values to null
Ripple was not generating events when setting values to null
- [ x] I have self-reviewed this PR
- [x ] I have added tests that prove the feature works or the fix is effective
=> Generate events when setting values to null

.github/workflows/Build.yml, core/main/src/firebolt/handlers/parameters_rpc.rs, core/main/src/firebolt/handlers/privacy_rpc.rs
=> fix: remove us-privacy from non us devices

core/main/src/firebolt/handlers/advertising_rpc.rs, core/main/src/firebolt/handlers/parameters_rpc.rs, core/main/src/firebolt/handlers/privacy_rpc.rs
=> fix: advertising config

core/sdk/src/api/config.rs, core/sdk/src/api/device/mod.rs, core/sdk/src/api/manifest/device_manifest.rs, examples/manifest/device-manifest-example.json, examples/manifest/mock/mock-device-manifest.json, examples/reference-manifest/IpStb/firebolt-device-manifest.json
=> Remove deprecated manifest fields and support

.github/workflows/Build.yml, core/main/src/firebolt/handlers/device_rpc.rs, core/main/src/firebolt/handlers/localization_rpc.rs, core/main/src/processor/storage/storage_manager.rs, core/main/src/service/apps/delegated_launcher_handler.rs, core/main/src/state/metrics_state.rs, core/sdk/src/api/device/device_peristence.rs, core/sdk/src/api/storage_property.rs, device/thunder_ripple_sdk/src/processors/thunder_persistent_store.rs, device/thunder_ripple_sdk/src/tests/contracts/thunder_persistent_store_pacts.rs
=> Update 1.8.rc with main

.github/workflows/Build.yml, Cargo.toml, core/sdk/src/api/manifest/device_manifest.rs
=> Remove fields from device manifests which echo default values (#537)

core/main/src/broker/endpoint_broker.rs, core/main/src/firebolt/handlers/advertising_rpc.rs, core/main/src/firebolt/handlers/parameters_rpc.rs, core/main/src/firebolt/handlers/privacy_rpc.rs, core/sdk/Cargo.toml, core/sdk/src/extn/client/extn_client.rs
=> Add ripple gateway rule for country code api

core/main/src/state/metrics_state.rs
change source for device_manufacturer and device_type
Authenticated/activated fields incorrect
If persistent storage doesn't provide a value for device_manufacturer and device_type, query thunder for the value.
Authenticated/activated fields should always be true
=> change source for device_manufacturer and device_type

core/main/src/broker/endpoint_broker.rs, core/main/src/broker/thunder_broker.rs, device/mock_device/src/mock_data.rs
Fix the endpoint_broker handling of error case.
=> RPPL-2100: Create JQ Rules for Secure Storage API

device/thunder_ripple_sdk/src/bootstrap/boot_thunder.rs, device/thunder_ripple_sdk/src/bootstrap/setup_thunder_pool_step.rs
=> RPPL-2297: Cleanup Panics in Ripple

Cargo.toml, core/main/Cargo.toml, core/sdk/Cargo.toml, device/thunder_ripple_sdk/Cargo.toml, examples/rpc_extn/Cargo.toml, openrpc_validator/Cargo.toml
=> Updated cargo.toml

.github/workflows/Build.yml, systemd/ripple.service
=> RPPL-2360: Update LOG level for ripple.service

core/main/src/firebolt/handlers/provider_registrar.rs, core/main/src/state/firebolt-open-rpc.json, core/sdk/src/api/firebolt/provider.rs
=> feat: Upgrade to firebolt 1.1.0

core/main/Cargo.toml, core/main/src/broker/rules_engine.rs
=> Fix jq parser 1.11.rc

core/main/Cargo.toml, core/main/src/broker/rules_engine.rs
=> fix JQ parser on filter that extracting json object

.github/workflows/Build.yml, core/main/src/broker/endpoint_broker.rs
=> Jq rule return type cla

.github/workflows/Build.yml, core/main/src/broker/endpoint_broker.rs, core/main/src/broker/thunder/thunder_plugins_status_mgr.rs
=> Merge 1.11

core/main/src/broker/endpoint_broker.rs, core/main/src/broker/rules_engine.rs
=> fix endpoint broker apply response parse json rpc response

.github/workflows/Build.yml, core/main/src/processor/storage/default_storage_properties.rs
=> StorageManager: Fixed default postal code returned for any key in app ID namespace.

core/main/src/processor/storage/default_storage_properties.rs
=> Cherry-pick 1.9.rc --> 1.12.rc

core/main/src/processor/storage/default_storage_properties.rs
=> Sync'd 1.9.rc --> 1.10.rc

.github/workflows/Build.yml, README.md, core/main/src/broker/endpoint_broker.rs
=> Sync 1.11.rc --> 1.12.rc

device/thunder_ripple_sdk/src/processors/thunder_wifi.rs
=> Updated thunder_wifi.rs

core/main/src/broker/endpoint_broker.rs, core/main/src/broker/rules_engine.rs, core/main/src/broker/thunder_broker.rs
Error Handling in JQ Rules
Errors not handled properly
Handle errors properly
Tested and result attached to the ticket
=> RPPL-2497: Error Handling in JQ Rules

.github/workflows/Build.yml, device/thunder_ripple_sdk/src/processors/thunder_device_info.rs
=> Ripple 1.13.0 to main merge

core/main/src/state/openrpc_state.rs
=> fix: Ripple: OpenRpcState.extended_rpc never updated

core/main/src/state/openrpc_state.rs
=> feat: add OpenRPC validator support for extension schemas

core/main/Cargo.toml, core/main/src/state/openrpc_state.rs, ripple
modifies load RPC based on features enabled using conditional compilation checks 
to resolve contract failure issue
added conditional compilation checks to dynamically change referred location for firebolt-open-rpc.json
concourse job succeed
=> RPPL-2592: contract failure issue

core/main/src/firebolt/handlers/account_rpc.rs, core/main/src/firebolt/handlers/device_rpc.rs, core/main/src/firebolt/rpc_router.rs, core/main/src/utils/common.rs, core/main/src/utils/mod.rs, core/main/src/utils/utils.rs, core/sdk/src/api/manifest/extn_manifest.rs, core/sdk/src/api/storage_property.rs
=> RPPL-2593 Device.uid is returning a value that contains dash

core/sdk/src/api/manifest/device_manifest.rs
=> Add country postal code to manifest

core/main/src/firebolt/handlers/privacy_rpc.rs, core/sdk/src/api/manifest/device_manifest.rs
=> add us_privacy string for any partner outside of US

device/thunder_ripple_sdk/src/tests/contracts/thunder_persistent_store_pacts.rs
=> update contract test response

core/main/src/bootstrap/extn/load_session_step.rs, core/sdk/src/framework/bootstrap.rs
=> Metrics initialization analysis

core/sdk/src/framework/bootstrap.rs
=> Metrics initialization analysis: Removed duplicate debug log.

core/main/src/broker/thunder_broker.rs
unit test's added for thunder_broker.rs 
verify the functionality and improve code coverage.
added new test cases.
Generated report locally to check the coverage improvement.
=> RPPL-2578: unit test's added for thunder_broker.rs 

core/sdk/src/extn/client/extn_client.rs
=> RPPL-2717: Auth Service Token update Race Condition

core/main/src/broker/thunder/thunder_plugins_status_mgr.rs
Added missing error propagation to End Point Broker
Callback notification was missing for invalid Plugin use case.
Added missing callback invocation 
Used JQ Rule with invalid Plugin Name (`alias`) to test this use case.
=> fix: Added missing Thunder Error code propagation to EndPoint Broker.

.github/workflows/Build.yml, openrpc_validator/src/lib.rs
=> OpenRPC Validator: Not always returning method result schema

.github/workflows/Build.yml, openrpc_validator/src/lib.rs
=> Merge 1.16.rc/2.0.rc --> main

core/main/src/firebolt/handlers/provider_registrar.rs, openrpc_validator/src/lib.rs
=> RPPL-2822: Ripple provider app-passthrough: Result wrapped in result "name" field from schema

core/main/src/processor/account_link_processor.rs
=> Rppl 2824: Change Default "completed" Value in Resume Point Request To False

core/main/src/firebolt/handlers/metrics_rpc.rs, core/main/src/processor/metrics_processor.rs, core/main/src/service/apps/delegated_launcher_handler.rs
=> Metrics.appInfo Returns 'Method not found': Implemented

core/main/src/processor/main_context_processor.rs, core/sdk/src/api/device/device_info_request.rs, core/sdk/src/api/manifest/device_manifest.rs, device/thunder_ripple_sdk/src/processors/thunder_device_info.rs
Remove hardcoding of Internet monitoring interval.  Used configured value from device manifest.
=> feat: Remove hardcoding of Internet monitoring interval. 

core/sdk/src/api/manifest/device_manifest.rs
=> feat: update default data governance policy

.github/workflows/Build.yml, core/main/src/processor/metrics_processor.rs
=> feat: RPPL-2846: [badger_extn]-Error sending badger metrics

systemd/ripple.service
=> Enable RUST_LOG=debug for RDKE

.github/workflows/Build.yml, core/main/src/processor/settings_processor.rs
Bug fix in handling `power_save_status` & `ShareWatchHistoryStatus` in `badger.subscribeToSettings`
=> fix: badger.subscribeToSettings Failing With power_save_status & ShareWatchHistoryStatus Keys

.github/workflows/Build.yml, core/main/src/processor/settings_processor.rs
=> Merge 1.19 to main

core/main/src/broker/endpoint_broker.rs, core/main/src/broker/thunder_broker.rs, core/main/src/broker/websocket_broker.rs, core/main/src/broker/workflow_broker.rs
=> feat: composite requet to support end point error response

core/sdk/src/api/device/device_operator.rs, device/thunder_ripple_sdk/src/client/plugin_manager.rs, device/thunder_ripple_sdk/src/client/thunder_client.rs, device/thunder_ripple_sdk/src/client/thunder_client_pool.rs, device/thunder_ripple_sdk/src/processors/thunder_package_manager.rs, device/thunder_ripple_sdk/src/processors/thunder_remote.rs, device/thunder_ripple_sdk/src/processors/thunder_wifi.rs
=> ThunderClient::subscribe(): Fixed unsafe unwrap()

core/main/src/broker/endpoint_broker.rs
=> Accessibility.onVoiceGuidanceSettingsChanged Event Doesn't Include Correct Fields

core/main/src/processor/store_user_grants_processor.rs
=> fix: Mismatch of expiration date between UserGrants.request and privacySettings responses.

core/main/src/broker/endpoint_broker.rs, core/main/src/firebolt/handlers/localization_rpc.rs
=> Update handler code for Localization.addAdditionalInfo and Localization.removeAdditionalInfo to use internal JQ calls

.github/workflows/Build.yml, core/main/src/broker/broker_utils.rs, core/main/src/broker/endpoint_broker.rs, core/main/src/firebolt/handlers/closed_captions_rpc.rs, core/main/src/firebolt/handlers/voice_guidance_rpc.rs, core/main/src/processor/settings_processor.rs, core/main/src/service/apps/app_events.rs, core/sdk/src/api/gateway/rpc_gateway_api.rs, core/sdk/src/api/manifest/exclusory.rs, device/thunder_ripple_sdk/src/client/thunder_plugin.rs, device/thunder_ripple_sdk/src/processors/events/thunder_event_handlers.rs
=> Badger.settings calls for closedcaptions state are going to persistent storage no usersettings plugin

.github/workflows/Build.yml, core/main/src/broker/broker_utils.rs, core/main/src/broker/endpoint_broker.rs, core/main/src/firebolt/handlers/closed_captions_rpc.rs, core/main/src/firebolt/handlers/voice_guidance_rpc.rs, core/main/src/processor/settings_processor.rs, core/sdk/src/api/gateway/rpc_gateway_api.rs, core/sdk/src/api/manifest/exclusory.rs, device/thunder_ripple_sdk/src/client/thunder_plugin.rs, device/thunder_ripple_sdk/src/processors/events/thunder_event_handlers.rs
=> RPPL-3118: Badger.settings calls for closedcaptions state are going to persistent storage no usersettings plugin

core/main/src/broker/broker_utils.rs, core/main/src/broker/endpoint_broker.rs, core/main/src/broker/thunder_broker.rs, core/main/src/broker/websocket_broker.rs, core/main/src/utils/test_utils.rs
=> add unit test

core/main/src/broker/endpoint_broker.rs, core/main/src/broker/extn_broker.rs, core/main/src/broker/http_broker.rs, core/main/src/broker/thunder_broker.rs, core/main/src/broker/workflow_broker.rs, core/main/src/state/bootstrap_state.rs, device/thunder_ripple_sdk/src/client/thunder_async_client_plugins_status_mgr.rs, device/thunder_ripple_sdk/src/client/thunder_client.rs
…ase the buffer size of ThunderBroker Request mpsc channel.
=> Use non-blocking try_send() API in BrokerRequestSender and increase the buffer size of ThunderBroker Request mpsc channel.

core/main/src/state/bootstrap_state.rs, core/sdk/src/api/manifest/cascaded_extn_manifest.rs, core/sdk/src/api/manifest/ripple_manifest_loader.rs, core/sdk/src/manifest/device.rs
=> Clean up read_env_variable() and log env variables

.github/workflows/Build.yml, core/main/src/broker/endpoint_broker.rs, core/main/src/broker/rules_engine.rs, device/thunder_ripple_sdk/src/client/thunder_async_client.rs
2.6.rc changes to main
Some changes directly added to rc branch to fix bug.
Bringing changes into main
Sanity validation and CI
=> 2.6.rc changes to main

core/main/Cargo.toml, core/main/src/broker/http_broker.rs, core/main/src/utils/test_utils.rs
Adding Unit test coverage for http_broker
Testing http_broker module.
Added mock HTTP server.
verified functionalities.
cargo test -- --nocapture -- http_broker
=> feat: unit test for http broker.

Cargo.lock, core/main/Cargo.toml, core/main/src/bootstrap/start_communication_broker.rs, core/main/src/broker/endpoint_broker.rs, core/main/src/broker/thunder/thunder_plugins_status_mgr.rs, core/main/src/broker/thunder_broker.rs, core/sdk/src/api/manifest/cascaded_device_manifest.rs, core/sdk/src/api/manifest/device_manifest.rs, device/thunder_ripple_sdk/src/bootstrap/boot_thunder.rs, device/thunder_ripple_sdk/src/bootstrap/setup_thunder_pool_step.rs, device/thunder_ripple_sdk/src/client/plugin_manager.rs, device/thunder_ripple_sdk/src/client/thunder_async_client.rs, device/thunder_ripple_sdk/src/client/thunder_async_client_plugins_status_mgr.rs, device/thunder_ripple_sdk/src/client/thunder_client.rs, device/thunder_ripple_sdk/src/client/thunder_client_pool.rs, device/thunder_ripple_sdk/src/client/thunder_plugin.rs
=> feat: RPPL-3165: check all thunder plugin status during broker start up

.github/workflows/Build.yml
=> merge main into 1.23.rc

core/main/src/service/apps/provider_broker.rs, ripple
=> Support for Multiple IPA providers

Cargo.lock, core/main/Cargo.toml, core/main/src/bootstrap/boot.rs, core/main/src/firebolt/firebolt_ws.rs, core/sdk/Cargo.toml, core/sdk/src/api/manifest/extn_manifest.rs, core/sdk/src/manifest/extn.rs
=> Code changes for standalone service impl

core/sdk/src/api/observability/metrics_util.rs
=> Invalid unit test assertions

.github/workflows/Build.yml, core/main/src/broker/endpoint_broker.rs, core/main/src/state/bootstrap_state.rs
=> fix: revert channel buffer size changes

.github/workflows/Build.yml, core/main/src/broker/endpoint_broker.rs, core/main/src/state/bootstrap_state.rs
1.24.rc changes into main
changes are missed in main.
sanity dev test.
=> fix: revert channel buffer size changes (#835)

core/sdk/src/api/manifest/cascaded_device_manifest.rs
updating mergeconfig logic for distributor_services fields.
to to merge config for all possible values.
added support for all types
cargo test -- --nocapture -- manifest_validation_tests
=> fix: updating mergeconfig logic for distributor_services fields.

core/main/src/firebolt/handlers/second_screen_rpc.rs
=> port secondscreen onFriendlyNameChanged event to JQ rule

Cargo.lock, core/main/src/bootstrap/boot.rs, core/main/src/bootstrap/manifest/apps.rs, core/main/src/broker/endpoint_broker.rs, core/main/src/broker/rules/rules_engine.rs, core/main/src/broker/workflow_broker.rs, core/main/src/firebolt/handlers/device_rpc.rs, core/main/src/processor/config_processor.rs, core/main/src/state/openrpc_state.rs, core/main/src/state/platform_state.rs, core/sdk/Cargo.toml, core/sdk/src/manifest/device.rs, core/sdk/src/manifest/extn.rs, core/sdk/src/utils/test_utils.rs
1st round of .clone() -> Arc<T> to drive down static RSS
=> Memory optimization phase 1

device/thunder_ripple_sdk/src/tests/contracts/thunder_device_info_pacts.rs, device/thunder_ripple_sdk/src/tests/contracts/thunder_text_track_pacts.rs, device/thunder_ripple_sdk/src/tests/contracts/thunder_user_settings_pacts.rs
=> RPPL-3456: contract test discrepancies resolved

core/main/src/bootstrap/boot.rs, core/main/src/bootstrap/manifest/apps.rs, core/main/src/bootstrap/manifest/device.rs, core/main/src/bootstrap/manifest/extn.rs, core/main/src/broker/endpoint_broker.rs, core/main/src/broker/rules_engine.rs, core/main/src/firebolt/handlers/device_rpc.rs, core/main/src/firebolt/rpc_router.rs, core/main/src/processor/config_processor.rs, core/main/src/state/openrpc_state.rs, core/main/src/state/platform_state.rs, core/sdk/Cargo.toml, core/sdk/src/processor/rpc_router.rs, core/sdk/src/utils/test_utils.rs
Back porting Memory Optimizations to 8.1
For better memory improved performance.
refactered and optimized code.
run memory profiling tool.
=> Backporting Memory Optimizations to 1.21.rc
