rdkcentral/Ripple

core/sdk/src/api/firebolt/fb_advertising.rs, core/sdk/src/extn/extn_client_message.rs
Reason for change: Adding Advertising struct .
Risks: Low
Test Procedure: Build and test api's.
Signed-off-by: kvfasil <fasil_KV@comcast.com>
=> fix: Adding Advertising struct to extn response. fixes #139

core/main/src/bootstrap/extn/check_launcher_step.rs, core/main/src/bootstrap/start_app_manager_step.rs, core/main/src/firebolt/handlers/lcm_rpc.rs
Lifecycle management processor is right now only available for Builds with launcher contract.
Change:
Lifecycle management processor can be used by proprietary protocol apis during app handling process.
=> fix: LCM Processor for non launcher contracts

core/main/src/state/extn_state.rs
The current implementation of Ripple 2.0 starts the extension on the same thread as the Tokio Runtime. Move this process to a separate thread so the Main Application's Tokio Runtime doesn't get affected.
This sometimes causes unexpected behavior to the green threads doing other operations within the main application.
Using std::thread create a separate new thread and pass on the Extn starting operation so the Memory container for the Extension executes on a different thread
=> fix: Move the Extension starter to a new thread

Cargo.toml, core/launcher/Cargo.toml, core/main/Cargo.toml, core/main/src/bootstrap/start_fbgateway_step.rs, core/sdk/Cargo.toml, core/sdk/src/api/apps.rs, core/sdk/src/api/device/device_peristence.rs, core/sdk/src/api/firebolt/fb_authentication.rs, core/sdk/src/extn/ffi/ffi_jsonrpsee.rs, core/sdk/src/extn/ffi/mod.rs, core/sdk/src/utils/logger.rs, device/thunder/Cargo.toml, device/thunder_ripple_sdk/Cargo.toml, distributor/general/Cargo.toml, docs/how-to.md, examples/rpc_extn/Cargo.toml, systemd/ripple.service
Rust supports conditional compilations using feature flags t
1. Build more light weight dependencies like adding jsonRpsee library and ffi only for required extensions.
2. Expand feature set like Running Ripple as a system d process.
1. Helps create more light weight dependencies for ripple-sdk
2. Helps Ripple abstract code for systemd specific and provides easy local development for non systemd runs.
1. Addition of 2 feature flags `rpc` for sdk and `sysd` for Main
2. Addition of `sd_notify` library for notifying system d services when ripple is ready
3. Improve logging as time is redundant as sysd process already adds the timestamp. But for running as a binary or local development we need the timestamp in logging
=> feat: Adding features for SystemD and RPC

core/main/Cargo.toml, core/sdk/Cargo.toml
Namespaced dependencies are not supported in older versions of rust. Change broke in Yocto as it has an older version of rust 1.58
```
| Caused by:
|   namespaced features with the `dep:` prefix are only allowed on the nightly channel and requires the `-Z namespaced-features` flag on the command-line
| WARNING: exit code 101 from a shell command.
| ERROR: Execution of '/home/jkuria217/skyxioneQ3/build-skyxione/tmp/work/armv7vet2hf-neon-rdk-linux-gnueabi/ripple/0.8.0-r0/temp/run.do_compile.467988' failed with exit code 101:
| error: failed to load manifest for workspace member
```
Yocto is yet to upgrade the older version of rust which has many deprecated features.
By reverting the changes for namespaced dependency and more implicit definition of dependencies
=> fix: Hotfix for 1.58 based compilers

core/main/src/firebolt/firebolt_ws.rs, core/main/src/firebolt/handlers/advertising_rpc.rs, core/main/src/firebolt/handlers/capabilities_rpc.rs, core/main/src/firebolt/handlers/device_rpc.rs, core/main/src/firebolt/handlers/voice_guidance_rpc.rs, core/main/src/processor/account_link_processor.rs, core/main/src/service/apps/delegated_launcher_handler.rs, core/main/src/state/cap/permitted_state.rs, device/thunder_ripple_sdk/src/processors/thunder_device_info.rs, device/thunder_ripple_sdk/src/processors/thunder_persistent_store.rs
Improved memory efficiency when using `PermissionHandler::fetch_and_store`.
As @Karthick-Somasundaresan pointed out in the review for https://github.com/rdkcentral/Ripple/pull/194 there were several items being cloned that didn't really need to be and this means that memory is not being used as efficiently as possible.
By taking the arguments for the associated function as references the need to clone data before passing in has been removed.
=> refactor: PermissionHandler::fetch_and_store args as reference

core/main/Cargo.toml, core/main/src/bootstrap/boot.rs, core/main/src/main.rs, core/main/src/service/telemetry_builder.rs
Need better exit procedure during bootstrap failures
Some devices have issues during bootstrap typically while connecting to underlying device API like Thunder. Current implementation in Ripple panics as a bootstrap error.
Better handling of Exit codes is required
1. Remove `expect` statements in bootstrap and replace with proper error handling procedures.
2. Add ExitCodes crate and provide a proper exit code during error scenarios.
=> fix: Exit with error code gracefully

device/thunder_ripple_sdk/src/tests/contracts/contract_utils.rs
Recently ExtnSender has been modified to have one more param config and contract test util would need the modification to accommodate that change for request creation.
=> Fixed Extn_Sender arg issue in contract test

Cargo.toml, core/launcher/Cargo.toml, core/main/Cargo.toml, core/main/src/firebolt/firebolt_ws.rs, core/main/src/firebolt/handlers/capabilities_rpc.rs, core/main/src/service/apps/provider_broker.rs, core/main/src/service/user_grants.rs, core/main/src/state/cap/cap_state.rs, core/main/src/state/cap/generic_cap_state.rs, core/main/src/state/cap/permitted_state.rs, core/main/src/state/platform_state.rs, core/main/src/utils/mod.rs, core/main/src/utils/test_utils.rs, core/sdk/Cargo.toml, core/sdk/src/api/device/device_user_grants_data.rs, core/sdk/src/api/firebolt/fb_capabilities.rs, core/tdk/Cargo.toml, core/tdk/src/gateway/mod.rs, core/tdk/src/gateway/rpc_gateway_api.rs, core/tdk/src/lib.rs, core/tdk/src/utils/mod.rs, core/tdk/src/utils/test_utils.rs, device/thunder/Cargo.toml, device/thunder_ripple_sdk/Cargo.toml, distributor/general/Cargo.toml, docs/how-to.md, examples/manifest/device-manifest-example.json, examples/rpc_extn/Cargo.toml, ripple
Fixed evaluation of user grant policy options. This addresses the issue raised [here](https://github.com/rdkcentral/Ripple/issues/199)
This is also the final warning/error detected by clippy which addresses the issue raised [here](https://github.com/rdkcentral/Ripple/issues/192)
The current implementation of the user grant options evaluation only looks at the first step in the first option of the grant policies set. This option has its first step executed even if the platform does not support it. The result of this execution is then used as the entire result of the options evaluation.
What should actually happen is the first option with all supported steps is executed and a grant/deny response produced from a combination of capability support and user actions.
The evaluate options loop …
=> fix: user grant option evaluation

device/thunder_ripple_sdk/Cargo.toml
Multiple redundant dependencies affecting the build
Pact consumer and other dependencies were creating transitive dependencies with multiple Pact crates 
Removing dependencies which are not used
=> Updated pact_consumer version to 1.0.0

.gitignore, core/main/src/service/apps/delegated_launcher_handler.rs, core/sdk/src/utils/time_utils.rs
This PR fixes an error when compiled on Rust 1.69.0
It is not compatible with Rustc 1.69.0
By replacing is_some_and function with is_none and unwrap separately.
The build should be completed without any error.
=> fix: fixing compilation error on rust 1.69.0

core/launcher/Cargo.toml, core/launcher/src/launcher_state.rs, core/launcher/src/manager/app_launcher.rs, core/sdk/src/api/manifest/apps.rs
What
Currently, Launcher Extension doesn't use the sessionId received back from Main and pass on to the app being launched.
Why
These changes were not implemented in lieu with just being used as a Certification platform. With Accelerator UI effort Ripple will be using Launcher for more than just certification so we need to launch apps with session id to the secure port.
=> 178 launcher extension needs to pass on session

core/main/src/firebolt/handlers/secure_storage_rpc.rs
SecureStorage.get is returning a result = " " if no value is present for a key.
Expected -
There result in the response should be "null"
Update securestorage.get() return param to be an optional string which is same as the upstream function return param so that we just return whatever is returned from upstream function.
Steps to reproduce :
1. Set a value for key foo as "test" using the SecureStorage.setForApp api
2. Do a get and check the result is the value we set(test)
3. Clear the value for key foo using SecureStorage.removeForApp api
4. Do a get with key=foo 
- [X ] I have self-reviewed this PR
=> Fix securestorage get return as blank

core/sdk/src/api/session.rs
Add custom fmt::Debug() and fmt::Display() functions for DistributorSession and mask token field
We don't want to have token in log messages.
Custom Debug and Display functions of DistributorSession / ActiveSession did not use token field
=> RPPL-975: Add custom fmt::Debug() and fmt::Display() functions for DistributorSession and mask token field

core/main/src/firebolt/handlers/authentication_rpc.rs, core/main/src/state/platform_state.rs, device/thunder_ripple_sdk/src/tests/contracts/contract_utils.rs
This PR fixes the problem caused by https://github.com/rdkcentral/Ripple/pull/231 where all auth calls return platform token type
To fix authentication firebolt APIs to return correct token types
By accommodating the token type in the request
Tested using device.
Reviewer can test it by cloning the change locally and executing Authentication.* [firebolt API ](https://developer.comcast.com/firebolt-apis/core-sdk/v0.14.0/authentication)calls
=> fix: Authentication always return Platform

core/sdk/src/api/manifest/device_manifest.rs
Supporting `urn:firebolt:apps:<string>` format for reserved app-type.
Firebolt example documentation shows old URN formats which are currently implemented by some firebolt users. We need to be back compatible to the old URN values to support those users.
Added mapping in Ripple to support the legacy urn format.
eg: Both the legacy format `urn:firebolt:apps:main` and the new XRN format `xrn:firebolt:application-type:main` are now supported. 
Testing was done using the following Request.
```
{
"jsonrpc": "2.0",
"id": 10,
"method": "discovery.launch",
"params": {
"appId": "urn:firebolt:apps:main",
"intent": {
"action": "section",
"data": {
"sectionName": "subscribe"
},
"context": {
"source": "voice"
}
}
}
}
```
The mapped app must register for discovery.onNavigateTo event
The following event …
=> feat: Add support for additional reserved appId.

core/sdk/src/utils/serde_utils.rs
Discovery.contentAccess API date-time format is forced to one particular format. 
Firebolt need to support all pattern of OpenRPC date-time format.
We need to support all pattern of OpenRPC date-time format.
Used DateTime::parse_from_rfc3339() function for validating the time passed by the caller.
Use Discovery.watched() or Discovery.contentAccess() API to validate the time used in the API
- [x ] I have self-reviewed this PR
=> fix: Discovery.contentAccess API date-time format is forced to one particular format

.github/workflows/Build.yml, rust-toolchain.toml
Sets the rust version in GitHub actions to 1.69.0
Currently the CI chain uses the latest rust version. This is causing confusion and problems when clippy warnings are different in CI to what they are on developer laptops. It also ensures that developers can set a version locally and not use APIs (e.g. `.is_some_and()`) which are not available in build chains using older rust versions.
Add a rust-toolchain.toml file in the root of the project. This enforces the correct versions are used in CI and local development.
Tested by checking the CI passes and the logs show a specific version of rust was installed.
https://github.com/rdkcentral/Ripple/actions/runs/6454392693/job/17519832131?pr=269#step:3:164
https://github.com/rdkcentral/Ripple/actions/runs/6454392693/job/17519831892?pr=269#step:3:1 …
=> build: fix rust version in CI

core/main/src/firebolt/handlers/privacy_rpc.rs
Adds support for PrivacySettingsStorageType:Sync to have same support as PrivacySettingsStorageType:Local 
We need these changes to make sure Ripple is implementing the privacy expectations for storage type of sync
Adds `Sync` arm to the existing `Local` arm
Use Privacy.settings Firebolt APi Call to get the settings
=> fix: Privacy Sync returning not implemented

core/launcher/src/manager/app_launcher.rs, core/launcher/src/manager/container_manager.rs
When UI Provide operations like Keyboard, Pin Challenge and User grants were processed lifecycle events were not sent.
Firebolt specification mandates apps to be provided with lifecycle events if they are registered
When provide operations are executed Lifecycle events are sent based on the implementation in Container Manager.
1. Use Refui as the System App
2. Trigger keyboard
=> fix: Launcher not sending events

core/main/src/firebolt/handlers/secure_storage_rpc.rs, core/sdk/src/api/device/device_request.rs, core/sdk/src/api/firebolt/fb_discovery.rs, core/sdk/src/api/firebolt/fb_secure_storage.rs, core/sdk/src/utils/serde_utils.rs
1. Need validations for SecureStorage api(s) w.r.t Key
2. Need validations for Localization.Language api set properties
3. Need validations for Discovery watchedInfo and EntitlementsData
To enforce the firebolt schemas specified in the OpenRPC.
By creating custom serializers which make sure that the incoming data is fully compliant to the RegEx specification.
RegEx used in the code matches the definition in the Open RPC.
Trigger calls for SecureStorage like Get,Set and Remove to validate the key specification.
Trigger Firebolt set call for Localization.language
Trigger Firebolt request for Discovery.contentAccess
=> fix: Serializers for SecureStorage and Language

core/main/src/firebolt/handlers/advertising_rpc.rs, core/sdk/src/api/storage_property.rs
Implement Advertising.skipRestriction & Advertising.onSkipRestrictionChanged manage APIs
Advertising.skipRestriction - To get the value of skipRestriction
Advertising.onSkipRestrictionChanged - To subscribe to notifications when the value of skipRestriction changes
Implement these APIs in advertising rpc
Make a request for `Advertising.skipRestriction` to get skip restriction value.
Subscribe to skip restriction changed event, then set skip restriction to a different value. Verify subscriber get notified for new skip restriction value.
=> feat: implement Advertising.skipRestriction & Advertising.onSkipRestrictionChanged manage APIs

core/sdk/src/api/firebolt/fb_metrics.rs
Addition of missing adding  missing device_timezone_offset field to model
Model was out of sync with downstream 
Field is added where appropriate
Manual test. Can be tested per usual manual testing procedure used by QA to test BI metrics
- [ x] I have self-reviewed this PR
- [ - I have added tests that prove the feature works or the fix is effective
=> fix: adding  missing device_timezone_offset field

device/thunder_ripple_sdk/src/client/thunder_client.rs, device/thunder_ripple_sdk/src/client/thunder_client_pool.rs
The current implementation of the ThunderPool doesn't actually unsubscribe on the correct client where it had subscribed. 
The current implementation uses an `in_use` Ordering::relaxed algorithm to find the unused client to shared the load
In a given pool 0th index(first) client would be preferred for all subscribe and unsubscribe operations
Launch Certification App with system ui
From FCA trigger `Lifecycle:Close` with a close reason for "Error". This will force remove the app
Trigger FCA again from System UI
Without the fix the relaunch wouldnt show System UI
=> fix: Thunder client (un)subscribe issue

core/main/src/service/user_grants.rs
Update request deny reason for when app state is unavailable to be `Capability cannot be used when app is not in foreground state due to requiring a user grant`
Error message for when app state is unavailable is returned as `{capability} is not available` 
Update deny reason
=> fix: should not store grant when app state is unavailable

core/main/src/firebolt/handlers/advertising_rpc.rs, core/main/src/firebolt/handlers/capabilities_rpc.rs, core/main/src/firebolt/handlers/privacy_rpc.rs, core/main/src/processor/settings_processor.rs, core/main/src/state/cap/cap_state.rs, core/main/src/state/cap/permitted_state.rs, core/main/src/utils/test_utils.rs, core/sdk/src/api/firebolt/fb_capabilities.rs, core/sdk/src/api/firebolt/fb_openrpc.rs
Add support for ignore rules for capabilities.info
Ignore rules defined in the manifest should be accounted for capabilities.info.
Adding the support to ignore the checks for app ids mentioned in the manifest
1. Setup the device manifest with the app_ignore_rules for the Exclusory field
2. Call capabilities.info from the ignored app
3. Validate the results
=> fix: capabilities info for app ignore

core/sdk/src/api/firebolt/fb_capabilities.rs
Update as_str() to convert cap event to string
Converts cap event to string instead of json string
Converts cap event to string instead of using serde json which serialize data structure as json string
=> fix: ripple sends wrong eventName

core/main/src/state/cap/permitted_state.rs, core/sdk/src/framework/file_store.rs
Adds support to create a folder if it doesnt exist before 
Cache folder might not exist in some of the device environments. 
By creating a folder in the desired path or verify the folder exists before the cache data is stored.
Delete the folder for the saved_dir in the manifest and start ripple
=> fix: Cache cases where folder is not created

core/main/src/bootstrap/extn/load_session_step.rs, core/main/src/processor/main_context_processor.rs, core/main/src/service/apps/delegated_launcher_handler.rs, core/main/src/state/cap/permitted_state.rs
On Boot clear PowerActive States. Every RIpple restart will be treated as a power recycle event
Use cached permissions only when there is no data
To ensure that the capability information has integrity alignment with the scope and TTL.
1. Use existing power active cleanup operation on boot
2. Swap the logic for checking local to only when there is an error
1. Set power Active usergrants and reboot verify if the grants are still available post reboot
2. Validate the permission cache locally after every launch
=> fix: handling for power active cleanup and caps

core/launcher/src/manager/app_launcher.rs, core/main/src/firebolt/handlers/metrics_rpc.rs, core/main/src/service/telemetry_builder.rs, core/sdk/src/api/device/device_accessibility_data.rs, core/sdk/src/api/device/entertainment_data.rs, core/sdk/src/api/firebolt/fb_metrics.rs, core/sdk/src/utils/error.rs
1. Add deserialization validations for calls namely Internal.initialize, ccSettings for preferredLanguages, remove none values in entity info and  version deserialization
2. Applauncher issue with bad app library with mismatching name and app_id
3. Feature cleanup in SDK to run unit tests locally 
These changes were having a lower priority and was not blocking 1.0.0. Changes are added to have these fixed by 1.1.0
Serialization were mainly updated with annotations 
Tested this locally by triggering Internal.initialize, ccSettings  and also setting up listeners for entity info
=> fix: Patch Schema and other 1.0.0 issues

core/main/src/firebolt/handlers/discovery_rpc.rs, core/main/src/processor/account_link_processor.rs, core/sdk/src/api/account_link.rs, core/sdk/src/api/firebolt/fb_discovery.rs
Cleanup Account Processor for Watched and WatchNext Api(s)
ProgressUnit for WatchNext needs to be different from the progress value of `watched_info` to allow the distributor to define the progress value.
Providing a new ProgressUnit gives the distributor the ability to configure. 
=> fix: Handling watched and watchNext scenarios

core/main/src/firebolt/handlers/wifi_rpc.rs, core/sdk/src/api/device/device_wifi.rs, core/sdk/src/api/wifi.rs, core/sdk/src/utils/serde_utils.rs
wifi.scan function was not accepting timeout value as an input param.
This fix is needed for making the implementation spec compliant.  
Added the optional timeout param as an input to wifi.scan API
=> fix: wifi.scan not honoring the type of timeout in parameter

core/main/src/firebolt/handlers/lcm_rpc.rs, core/main/src/service/apps/delegated_launcher_handler.rs, core/main/src/utils/rpc_utils.rs, core/sdk/src/api/apps.rs
In order to support the launcher "resuming" apps where they were left off, Ripple should support a new app session with no intent. The app is just brought to the foreground and should not react to any user intent.
Ripple MUST return an error if no intent is given and this is creating a new running session. An app MUST be able to get their cold launch intent through Parameters.initialization. Return an error back to the caller of LifecycleManagement.session for this case. The error code can be -40000 and the message like "An intent must be provided for new app running sessions".
For cases where this is a new active session but not a new running session, if no intent is given, then the navigateTo call for the app is simply not called.
How has this been …
=> feat: Handle undefined intents in LifecycleManagement.session

core/main/src/processor/main_context_processor.rs
Partner exclusion sync functionality was missing.
Ripple storage needs to be synced up with partner exclusion data on boot up. 
Reintroduced `sync_partner_exclusions` function 
=> fix: Added sync_partner_exclusions API to fetch partner exclusion data

core/main/src/firebolt/handlers/metrics_management_rpc.rs, core/main/src/state/metrics_state.rs
Assign default string to device_session_id in context 
session id in metric payload is empty
=> fix: session_id in Metrics Payload is Empty

core/main/src/processor/metrics_processor.rs
PR adds the partner id in the context
PartnerId used within AppContext needs to be added by the context processor it was missing this entry
By using the partner identification information available in platform state and updating context
After the changes were made logs for BehaviorMetricsContext would not contain partner.id.not.set in the request
=> fix: Add Missing partner id in context

core/main/src/firebolt/handlers/advertising_rpc.rs, core/main/src/firebolt/handlers/parameters_rpc.rs, core/main/src/firebolt/handlers/privacy_rpc.rs, core/sdk/src/api/firebolt/fb_advertising.rs
Enhance Advertising.advertisingId so that an optional scope can be passed from an app
This changes is needed to meet implementation spec compliant
=> chore: enhance advertising.advertisingId API

core/main/src/service/user_grants.rs, core/main/src/state/openrpc_state.rs, core/sdk/src/api/firebolt/fb_openrpc.rs
When the user grants policy has an entry for a privacy setting, the property (privacy method) will be checked to validate certain conditions.
To ensure backward compatibility of Firebolt API, the module part of the method needs to be compared in a case-insensitive manner. This was missing in the current implementation
=> fix: Grant check fails to do case-insensitive comparison of privacy settings method

core/main/src/firebolt/firebolt_gateway.rs, core/main/src/processor/main_context_processor.rs
=> fix: Unsafe unwraps on session and message

core/main/src/processor/metrics_processor.rs, device/thunder_ripple_sdk/Cargo.toml
PR adds the partner id in the context
PartnerId used within AppContext needs to be added by the context processor it was missing this entry
By using the partner identification information available in platform state and updating context
After the changes were made logs for BehaviorMetricsContext would not contain partner.id.not.set in the request
=> fix : cherry-pick Add Missing partner id in context (#356)

core/main/src/processor/main_context_processor.rs, core/sdk/src/extn/client/extn_client.rs
Fixes context updates broadcasting between main and extensions 
Extensions need to know when ripple context like Token, PowerChanged, Internet are updated. Recent changes in the IEC channel broke the sender. This change fixes it
Uses try_send method instead of send method which addresses the issue as send returns a future and doesnt actually send the message to the extensions.
On Ripple startup each extension gets the list of Ripple context updates for Token, InternetStatus and Power status of the device.
=> fix: Context update

core/main/src/bootstrap/extn/load_session_step.rs, core/main/src/processor/main_context_processor.rs, core/main/src/service/context_manager.rs
Changes for #379  Caused an infinite loop of token updates.
There was no check for tokens before updating it first time.
Checking for the presence of tokens before updating.
=> fix: stop updating token in a loop

core/sdk/src/api/device/entertainment_data.rs
Makes intents deseralization more forgiving
Some systems may be sending intents that are not 100% to the firebolt spec with minor differences. Such as casing of enumeration values or leaving off fields that can be easily assumed. It is better for Ripple to not fail on these cases
If an intent is missing the field entityType, but has the field programType. We can infer that entityType should be "program" and parse as if it is a program entity.
Make programType handle some other common casing options for the enumeration value. For example before this change, Ripple would only accept intents with programType=movie, after the change it can accept Movie and MOVIE.
Have an app subscript to Discovery.onNavigateTo.
Call LifecycleManagement.session with an intent like:
```
{
"action": "entity", …
```
=> Intent forgiving

.github/workflows/Build.yml
Given that the vast majority of our target devices use the aarch64 ISA, it would be beneficial to run a build and test using that architecture. Since Github runners use x64, we have to use qemu to emulate both the build and test environment. There is a signifact performance penalty when using qemu. It might be possible to do the build using the aarch64-unknown-linux-gnu toolchain on x64 and just run the unit tests in the qemu environment, but it would require the sysroot and rootfs to be binary compatible.
Difference in types (especially when using FFI functions) can cause compilation errors. This ensure that future changes must pass both x64 and aarch64 workflows inorder to be considered for a merge into master.
By using qemu, we are able to confirm that Ripple can compile on aarch64, …
=> Added aarch64 workflow

core/main/src/firebolt/handlers/metrics_rpc.rs, core/sdk/src/api/firebolt/fb_metrics.rs
The API response is returned as the following currently:
```
{
"name": "Default Result",
"value": {
"version": {
"major": 1,
"minor": 0,
"patch": 0,
"readable": "Firebolt FEE 1.0.0"
}
} 
```
This PR fixes internal.initialize response to be like:
```
{
"version": { 
"major": 1, 
"minor": 0, 
"patch": 0, 
"readable": 
"Firebolt FEE 1.0.0" 
} 
}
```
To compliant with the Firebolt specification
=> fix: internal.initialize response

.github/workflows/Build.yml, CODEOWNERS.md, core/main/src/service/telemetry_builder.rs, core/sdk/src/api/firebolt/fb_metrics.rs, core/sdk/src/api/observability/metrics_util.rs, device/thunder_ripple_sdk/Cargo.toml
Changes to support describing ops metrics histograms
Support of differentiated bucket distributions for firebolt vs service interaction metrics
Type/parameter added to allow caller to denote which type (firebolt,svc) of metric is being created
Manually tested locally against dev otel endpoint
- [X ] I have self-reviewed this PR
=> feat: histogram support for ops metrics

core/main/src/bootstrap/extn/start_extn_channel_step.rs, core/sdk/src/api/device/device_request.rs, device/thunder_ripple_sdk/src/bootstrap/setup_thunder_pool_step.rs, device/thunder_ripple_sdk/src/client/plugin_manager.rs, device/thunder_ripple_sdk/src/client/thunder_client.rs, device/thunder_ripple_sdk/src/processors/thunder_device_info.rs, device/thunder_ripple_sdk/src/tests/thunder_client_pool_test_utility.rs, device/thunder_ripple_sdk/src/utils.rs
The current handling of Thunder plugins does not take into account activation states
Thunder client cannot make calls to a plugin that is not yet activated.
Established a new struct we can build this more going forward for any incoming messages
```#[derive(Debug, Deserialize)]
pub struct ThunderError {
pub code: i32,
pub message: String,
}
impl ThunderError {
pub fn get_plugin_state(&self) -> PluginState {
match self.message.as_str() {
"ERROR_INPROGRESS" | "ERROR_PENDING_CONDITIONS" => PluginState::InProgress,
"ERROR_UNKNOWN_KEY" => PluginState::Missing,
_ => PluginState::Unknown,
}
}
}
```
2. Updated the Ready method to serve more value. This will now add timeout logic
```
pub async fn ready(self) { -> pub async fn ready(self) -> bool
```
3. Activate Plugin now returns the status for In …
=> Thunder plugin handling

device/thunder_ripple_sdk/src/bootstrap/setup_thunder_pool_step.rs, device/thunder_ripple_sdk/src/client/plugin_manager.rs
Increase the support for handling Thunder states provided by the status call for a Thunder plugin
Ripple has to be aware of the thunder state before making a call to Thunder.
Including all the states listed under https://rdkcentral.github.io/Thunder/plugin/lifecycle/
Unit tests are included this will be tested in an environment where Thunder Plugins have a delayed startedup.
=> fix: Handling Thunder status for plugin

core/sdk/src/api/firebolt/fb_capabilities.rs, core/sdk/src/extn/client/extn_client.rs
1. Added error mapping in Firebolt sdk for `GrantProviderMissing` error returned from usergrants service layer. 
2. Extn client will skip processing invalid messages received by the message handler.  
1. The error code and message description returned when usergrants check failed due to GrantProviderMissing was incorrect.  
2. Extn client proceeded to use an invalid message, which caused a panic. 
=> fix: Wrong Error Message Returned When No Provider For UserGrant

core/main/src/firebolt/handlers/authentication_rpc.rs, device/thunder_ripple_sdk/src/client/plugin_manager.rs, device/thunder_ripple_sdk/src/client/thunder_client_pool.rs
Some Thunder plugins are created dynamically. Ripple needs to understand these plugins and have support for their activation
To support Thunder plugins which are added dynamically to the framework.
Uses the existing subscriber mechanism to setup state subscribers and provide the support.
Using a dynamic app plugin launched by RDKShell.launch
I have self-reviewed this PR
I have added tests that prove the feature works or the fix is effective
=> Dynamic plugin 1.5

core/main/src/firebolt/handlers/privacy_rpc.rs, core/main/src/processor/storage/storage_manager.rs, core/main/src/processor/store_privacy_settings_processor.rs, core/main/src/service/data_governance.rs, core/main/src/state/metrics_state.rs, core/main/src/state/platform_state.rs, core/main/src/state/ripple_cache.rs, core/sdk/src/api/distributor/distributor_privacy.rs, device/thunder_ripple_sdk/src/tests/thunder_client_pool_test_utility.rs
Privacy data Call Optimization, caching privacy settings values
In order to increase the resiliency and improve the latency of critical calls related to app launching we would require Ripple to Synchronize the values for privacy on boot and during linchpin updates in Platform State.
We expect some performance improvements in terms of latency for Privacy related api calls like
```
Parameters.initialization
Privacy Settings
Badger calls related to privacy.
```
Use cache for privacy settings storage properties 
=> fix: Privacy data Call Optimization, caching privacy settings values

distributor/general/src/distributor_general_ffi.rs, distributor/general/src/general_distributor_token_processor.rs, distributor/general/src/general_paltform_token_processor.rs, distributor/general/src/lib.rs, examples/reference-manifest/IpStb/firebolt-device-manifest.json, examples/reference-manifest/IpStb/firebolt-extn-manifest.json
few FCA test cases like wifi.scan(), Authentication.token Apis are failing.
wifi.scan issue:
rdk6 introduced firebolt-supported ResidentAppUI as the home UI,
hence the FCA app runs as a third-party app. In the app manifest, the ResidentAppUI has all the necessary access (referred to as refui in the app manifest).
Authentication.token Apis issue:
we have removed the support for token from the manifest because our device does not support it. However, there have been recent changes on the Ripple side, where they added platform.token and distributor.token hence we can mock the expected response as a reference.
wifi.scan issue:
The FCA app is now launched with the app ID "comcast.test.firecert". provided full access(exclusory).
Authentication.token Apis issue:
Added require contracts and …
=> Rdk 6.1 fixes for FCA test failures.

core/launcher/src/manager/app_launcher.rs, core/launcher/src/manager/container_manager.rs, core/launcher/src/manager/view_manager.rs, core/main/src/firebolt/firebolt_gatekeeper.rs, core/main/src/firebolt/handlers/closed_captions_rpc.rs, core/main/src/firebolt/handlers/discovery_rpc.rs, core/main/src/firebolt/handlers/localization_rpc.rs, core/main/src/firebolt/handlers/metrics_rpc.rs, core/main/src/firebolt/handlers/privacy_rpc.rs, core/main/src/firebolt/rpc_router.rs, core/main/src/processor/account_link_processor.rs, core/main/src/processor/main_context_processor.rs, core/main/src/processor/storage/storage_manager_utils.rs, core/main/src/service/apps/app_events.rs, core/main/src/service/apps/delegated_launcher_handler.rs, core/main/src/service/user_grants.rs, core/main/src/state/openrpc_state.rs, core/sdk/src/api/device/device_browser.rs, core/sdk/src/api/device/device_user_grants_data.rs, core/sdk/src/api/firebolt/fb_metrics.rs, core/sdk/src/api/gateway/rpc_gateway_api.rs, core/sdk/src/extn/client/extn_sender.rs, core/sdk/src/extn/extn_id.rs, core/sdk/src/framework/bootstrap.rs, device/thunder_ripple_sdk/src/bootstrap/setup_thunder_pool_step.rs, device/thunder_ripple_sdk/src/client/thunder_client.rs, device/thunder_ripple_sdk/src/client/thunder_client_pool.rs, device/thunder_ripple_sdk/src/processors/thunder_device_info.rs, device/thunder_ripple_sdk/src/utils.rs
CC:  [StefanBossbaly:remove_unwraps](https://github.com/StefanBossbaly/Ripple/tree/remove_unwraps)
Removes ~90 `.unwrap()` calls in favor of other Rust programming paradigms that prove the state of the enum instead of generating a `panic!()` on unexpected case.
Most the the replaced code was written like so, with the conditional check to handle the unwanted variant (`None` in this case) and then the call to `unwrap() `to extract the value.
```
if entry.is_none() {
error!(
"on_app_state_change: app_id={} Not found",
state_change.container_props.name
);
return;
}
// safe to unwrap
let app = entry.unwrap();
```
However `unwrap()` under the hood is just a `panic!` when the `None` variant is encountered like so.
```
if entry.is_none() {
error!(
"on_app_state_change: app_id={} Not found", …
```
=> Remove unsafe unwraps

core/main/src/state/cap/generic_cap_state.rs
This PR changes are for properly marking the availability of capability
When a cap is not supported it should be marked as unavailable. 
Before checking for availability it checks if it is supported. 
=> fix: Fix for marking unsupported caps as unavailable.

core/main/src/firebolt/handlers/metrics_rpc.rs, core/sdk/src/api/manifest/device_manifest.rs
Support for resume points using `metrics.mediaprogress` API.
This feature is turned off by default. 
Set the device manifest flag `mediaProgressAsWatchedEvents` to true under `default_values` section to turn on this feature.
=> feat: Support for resume points using metrics.mediaprogress

core/main/src/processor/storage/default_storage_properties.rs, core/main/src/processor/storage/storage_manager.rs, core/sdk/src/api/manifest/device_manifest.rs
Set a default value for accessibility.audioDescriptionSettings firebolt API
Ripple StorageManager to return a default value for audioDescriptionEnabled when the corresponding entry is not available in Thunder Persistent Storage.
=> set default value for audioDescriptionEnabled

core/main/src/firebolt/handlers/device_rpc.rs
Remove CARGO_PKG_VERSION dependency in device.version
CARGO_PKG_VERSION is the value of version in the Cargo.toml file for Ripple.
Use the version from Platform State by default. Use CARGO_PKG_VERSION as a backup if version is not available in platform state.
=> fix: Remove CARGO_PKG_VERSION dependency in device.version

core/main/src/firebolt/handlers/discovery_rpc.rs, core/main/src/processor/account_link_processor.rs, core/main/src/service/apps/delegated_launcher_handler.rs, core/sdk/src/api/manifest/device_manifest.rs
Added app lifecycle state transition validation.
Current implementation allows state transition to `suspended` or `unloading` directly from `foreground`/`background`.
This has been fixed by including a state transition validation function
Added the function `fn is_valid_lifecycle_transition(from: LifecycleState, to: LifecycleState) -> bool` to validate the app lifecycle state transition.
This validation check is disabled by default.  Set the feature flag `"lifecycle_transition_validate":true`  in device manifest to enable this check. 
=> LifecycleManagement.setState - Added state transition validation 

systemd/ripple.service
=> RPPL-2360:Update LOG level for ripple.service

core/main/src/broker/thunder/thunder_plugins_status_mgr.rs
Removed unused `startmode` filed from PluginStatus response.
It's an optional field and currently not used in Ripple. This was causing a deserialization error in parsing Status response from Controller as not all plugin status response includes startmode in the response message
Removed this field from Status structure.
=> fix: Removed startmode from Plugin State Status structure

core/main/src/firebolt/rpc_router.rs, core/main/src/processor/metrics_processor.rs, core/main/src/service/telemetry_builder.rs, core/sdk/src/api/firebolt/fb_telemetry.rs
FIRECERT-2189 Changes to send response in the fireboltInteraction logs
Added response field in fireboltInteraction.
=> Changes to send response in the fireboltInteraction logs

core/main/src/broker/thunder/thunder_plugins_status_mgr.rs
Bug fix 
This fix is required to process all pending broker requests upon receiving response of plugin status command, irrespective of the activation status
=> fix: Bug fix in on_status_response() function

.github/workflows/Build.yml, core/main/src/broker/thunder/thunder_plugins_status_mgr.rs
* fix: Bug fix in on_status_response() function of thunder_plugins_status_mgr
* fix: expiry related info log messages changed to error messages
* fix: fmt error fix
=> fix: [cherry-pick] Bug fix in on_status_response() function (#577)

core/sdk/src/utils/logger.rs
added the log filter based on crate names like h2, hyper, tower, tower_http, rustls, jsonrpsee_client_transport, jsonrpsee_core with the log level as OFF
to cutdown the unnecessary log capturing in the production build
apply log level filter using the crate names and mention log level as OFF 
run the bootup sequence and checked the logs before and after these changes.
=> refactor: Filtering logs

core/main/src/firebolt/handlers/advertising_rpc.rs
inverse the value updated by get_allow_app_content_ad_targeting().
get_allow_app_content_ad_targeting() inversion value should be update to  ad_opt_out.
inversing the value updated by get_allow_app_content_ad_targeting()
https://ccp.sys.comcast.net/browse/RPPL-2407  refer this task for some test input's
=> RPPL-2407: fix:ad_opt_out for Advertising.config.

core/sdk/src/api/storage_property.rs
this PR Remove the unused StorageProperty::UserGrants
StorageProperty::UserGrants is not used anywhere else so cleanup done.
StorageProperty::UserGrants removed it's declaration and definitions as well.
it's no where else used so 
=> RPPL-2150:refactor:cleanup done for StorageProperty::UserGrants which is unused

core/main/src/firebolt/handlers/provider_registrar.rs, core/main/src/state/cap/cap_state.rs, core/main/src/state/openrpc_state.rs, core/main/src/state/platform_state.rs, core/sdk/src/api/manifest/extn_manifest.rs
Provider registrations are hard coded in ripple, making it configurable.
Hard coded configurations are not scalable for extension sdks.
Having a default set of configurations and allow it to be overridden by manifests
Test without any manifest changes and make sure all the provider pattern works
Add an entry in provider_registrations for extension manifest and check if other providers fail with method not found.
=> feat: Configurable Provider Registrations

core/main/src/broker/endpoint_broker.rs, core/sdk/src/api/gateway/rpc_gateway_api.rs
Firebolt Ripple JQ Rules: Support for static response data
=> RPPL-2452: Firebolt Ripple JQ Rules: Support for static response data

core/main/src/firebolt/handlers/provider_registrar.rs, core/sdk/src/api/firebolt/provider.rs
Currently Provider errors are not handled for Providers outside Pin Challenge and Acknowledge Challenge
Original changes were focused on the Response payloads.
By providing a Generic Error Payload as a default parser for any Provider Responses before throwing errors.
Using Error Type object for Any API call outside Acknowledge Challenge and Pin Challenge
=> fix: Handling for Provider Error for generic

.github/workflows/Build.yml, device/thunder_ripple_sdk/src/processors/thunder_device_info.rs
slightly modify the get_hdcp_status(), and removed unnecessary functions related hdcp_status update
thunder api invoke each time upon receiving badger.capabilities 
correct hdcp status get updated from thunder, instead of taking from cache.
plugin/out hdmi cable then status checked correct values updated.
=> 2445_fix: thunder api get invoke whenever badger_capabilities triggered

core/main/src/firebolt/handlers/provider_registrar.rs, core/sdk/src/api/firebolt/provider.rs
Provider Error methods add the json rpc error on the result field 
The handling of a Generic Error enumeration is identical to that of a standard response.
Separating the error handling compared to response handling.
Calling AcknowledgeError, PinChallengeError and expect the error to be encapsulated in an error object
=> fix: Provider Error method should trigger

core/main/src/bootstrap/start_fbgateway_step.rs, core/main/src/broker/endpoint_broker.rs, core/main/src/broker/event_management_utility.rs, core/main/src/broker/rules_engine.rs, core/main/src/firebolt/firebolt_gateway.rs, core/main/src/firebolt/firebolt_ws.rs, core/main/src/firebolt/handlers/privacy_rpc.rs, core/main/src/firebolt/rpc_router.rs, core/main/src/processor/storage/default_storage_properties.rs, core/main/src/processor/storage/storage_manager.rs, core/main/src/service/apps/app_events.rs, core/main/src/service/telemetry_builder.rs, core/main/src/service/user_grants.rs, core/main/src/state/bootstrap_state.rs, core/main/src/state/cap/generic_cap_state.rs, core/main/src/state/openrpc_state.rs, core/main/src/utils/router_utils.rs, core/sdk/src/api/gateway/rpc_gateway_api.rs, core/sdk/src/extn/client/extn_client.rs, core/sdk/src/framework/bootstrap.rs, examples/rpc_extn/src/rpc/legacy_jsonrpsee_extn.rs, openrpc_validator/src/lib.rs
Adds better logging to help triage and measure telemetry
Telemetry currently offered in Ripple is very limiting, there is a need for measuring the time taken in each stage for every request.
Some of the Ripple logging have been too verbose for triaging and some production logs are lacking to help investigate issues faster.
By addition of RpcStats object to RPCRequest during request processing and API message for Response dispatching
Tested by making calls to multiple Firebolt APIs and validating the logs
=> feat: Upgrade Telemetry and better logging levels

core/main/src/broker/endpoint_broker.rs, core/main/src/broker/rules_engine.rs, core/main/src/broker/thunder/mod.rs, core/main/src/broker/thunder/user_data_migrator.rs, core/main/src/broker/thunder_broker.rs
=> feat: Implement UserDataMigrator Framework - Rule based Shim Layer

core/main/src/firebolt/handlers/account_rpc.rs, core/main/src/firebolt/handlers/device_rpc.rs
=> feat: create rules for Authentication and Account modules

core/main/src/firebolt/firebolt_gateway.rs, core/main/src/firebolt/handlers/provider_registrar.rs, core/main/src/state/openrpc_state.rs, openrpc_validator/src/lib.rs
=> fix: openRPC validation

core/main/src/broker/thunder_broker.rs, core/sdk/src/extn/client/extn_client.rs, device/thunder_ripple_sdk/src/processors/thunder_device_info.rs
add check for event listener's for context events.
if there are no event listeners available then no need to warn
added check for event listeners availability based on that print the warn!
if context event listeners available then warn! msg prints if not then warn! msg wont print.
=> RPPL-2651: Ripple Event warning should not print for context events

core/main/src/firebolt/handlers/provider_registrar.rs, openrpc_validator/src/lib.rs
=> Ripple provider app-passthrough: Result wrapped in result name field from schema

core/main/src/broker/endpoint_broker.rs
Skipped Thunder Endpoint creation when setting up OtherBrokers.
ThunderBroker instances are created at multiple places. 
=> fix: Multiple instances of Thunder Broker created during Ripple bootstrap

core/sdk/src/api/firebolt/fb_metrics.rs, core/sdk/src/api/firebolt/fb_telemetry.rs
Fixed the data structure for ErrorParams in Metrics.error
Vector of Params{String, FlatMapValue} structure was used instead of HashMap<String, FlatMapValue>
HashMap<String, FlatMapValue> has been used for parameters in ErrorParams struct
=> fix: RPPL-2831 : Metrics.error Calls With "parameters" are Failing.

core/main/src/broker/thunder/user_data_migrator.rs
Decoupled user data migration status from migration configuration. 
Migration status is managed internally by Ripple source code.  This status value should not be mixed with settings/configuration file.
=> feat: Decouple Migration Status flag from Configuration

device/thunder_ripple_sdk/Cargo.toml, device/thunder_ripple_sdk/src/tests/contracts/contract_utils.rs, device/thunder_ripple_sdk/src/tests/contracts/thunder_controller_pacts.rs, device/thunder_ripple_sdk/src/tests/contracts/thunder_device_info_pacts.rs, device/thunder_ripple_sdk/src/tests/contracts/thunder_persistent_store_pacts.rs, device/thunder_ripple_sdk/src/tests/contracts/thunder_remote_pacts.rs
Use a thin websocket client to send thunder call message to pact server instead of using thunder extension processor and Thunder client pool 
Many of the thunder extension processing functions are removed as Ripple is now using Rule Engine.
Rippple is migrating to AsyncThunderClient and will be removing the usage of Thunder ClientPool  
=> feat: Create an RDK contract test framework using generic client.

core/main/src/firebolt/handlers/metrics_rpc.rs, core/sdk/src/api/firebolt/fb_metrics.rs
Changing Metrics.mediaRenditionChange rate field into json Number type
spec define the field is number, that either a integer or float
changes rate field into json Number type
invoke Metrics.mediaRenditionChange api.
=> Changing Metrics.mediaRenditionChange rate field into json Number type.

core/main/src/firebolt/firebolt_gateway.rs
reverting session id cleanup due to VG issue.
cid changed into sessionid as part of cleanup.
reverted the change
VG in amazon
=> fix : reverting session id cleanup due to VG issue.

Cargo.toml, core/main/Cargo.toml, core/main/src/state/openrpc_state.rs, openrpc_validator/Cargo.toml
1. Made OpenRPC validation support optional in the Ripple repository.
2. Added the openrpc_validation feature flag in Cargo.toml to conditionally include the openrpc_validator dependency.
3. Marked openrpc_validator as an optional dependency, only enabled when the feature is specified.
4. Updated the workspace Cargo.toml to exclude openrpc_validator from the default build.
5. Refactored openrpc_state.rs to use conditional compilation:
When the openrpc_validation feature is enabled, real validation logic is used.
When disabled, dummy types and no-op methods are provided, allowing the code to compile and run without validation.
This change reduces build size and dependencies for default builds, while still allowing full OpenRPC validation when needed.
How do …
=> feat: Move the openRPC schema validation crate under a feature flag and disable it by default

core/main/src/service/apps/provider_broker.rs
There is no provider subscribed we are waiting for a timeout error instead we should be erroring immediately stating no provider.
As expect immediately respond back as error.
instead of waiting responded back as error.
integrated players tests
=> fix: if no provider there sending error response.
